title: Gabi's page
logo: https://github.com/G-a-b-b-s/G-a-b-b-s.github.io/blob/5bb38202689df29964537f536785d8d058833db3/ch.png
description:           This is my IT page
google_analytics:
theme: jekyll-theme-minimal
